### PR TITLE
Update ElkNode type

### PR DESCRIPTION
**Pull request by Connor-Wallace**
Thanks for this library it's a great way to render dags. While using this in one of my projects I noticed an issue with the typings, `ElkNode` types the edges field to `ElkEdge[]` but the actual value aligns with the `ElkExtendedEdge` type.

### CODE REVIEW

**Comment by uruuru** [comment]
Thanks for initiating the PR. 

I came across this before but wasn't happy with the solutions that popped into my head: Actually it's `ElkPrimitiveEdge | ElkExtendedEdge`, with the latter being the type to be returned (always) and the former being allowed as input. 

Maybe a complete solution would be to have different types for input and output graphs. The input would allow the alternative and the output clearly states `ElkExtendedEdge`.

**Comment by Connor-Wallace** [comment]
@uruuru 

Ah interesting. I think you're idea makes the most since because the `ElkNode` type is recursively referenced in `children` field and will need to be updated depending on if it is an input or output graph so we can just make this change where we declare the output for `layout`. I've added some additional input and output types to this PR.

**Comment by uruuru** [comment]
It would be good if it, additionally, doesn't break existing code. Maybe `type ElkNode = ElkInputNode` is enough. Not sure about the `ElkEdge` though without testing it. 
Feel free to add something if you have a thorough solution. Otherwise I'll try to have a look once I find time.

**Comment by Connor-Wallace** [comment]
I probably wrongly assumed that anyone using these types was asserting to the values necessary. I've added `ElkNode` back in and created a conditional return type based on the graph type.

**Pull request merged**
